import type { Metadata } from "next";
import "@/styles/global.scss";
import { plusJakartaSans } from "../src/utils/fonts";
import Header from "@/components/global/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>
        <Header />
        <main id="main">{children}</main>
      </body>
    </html>
  );
}
