import type { Metadata } from 'next';
import '@/global/global.scss';
import { cityStreetwearTtf, cityStreetwearWoff, cityStreetwearWoff2, lato, plusJakartaSans } from '../src/global/fonts';
import Header from '@/components/global/Header';
import Footer from '@/components/global/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${plusJakartaSans.className} ${lato.variable} ${cityStreetwearTtf.variable} ${cityStreetwearWoff.variable} ${cityStreetwearWoff2.variable}`}
      >
        <Header />
        <main id='main'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
